algoritmo "areaquadrado"
"Exercício I"
var
  lado, area: real
  
inicio
   escreval("--------------------------------------")
   escreval("CÁLCULO DA ÁREA DO QUADRADO")
   escreval("--------------------------------------")
   escreval("------------------------------------")
   escreval("Digite o valor do lado do quadrado: ")
   escreval("------------------------------------")
   leia(lado)

   area <- lado*lado
   
   escreval("O valor da Área do quadrado digitado vale: ", area)
fimalgoritmo
