algoritmo "mediaaritmetica"
"Exercício IV"
var
v1, v2, v3, M  : real
  
inicio
escreval("-------------------------------------")
escreval("Média de valores")
escreval("-------------------------------------")

escreval("-------------------------------------")
escreval("Digite o valor de A")
escreval("-------------------------------------")
leia(v1)

escreval("-------------------------------------")
escreval("Digite o valor de B")
escreval("-------------------------------------")
leia(v2)


escreval("-------------------------------------")
escreval("Digite o valor de C")
escreval("-------------------------------------")
leia(v3)

M <- (v1+v2+v3)/3

escreval("O valor da média aritmética dos três valores é: ", M:3:2)



fimalgoritmo
