algoritmo "quadrados"
"Exercício 9"
var
A, B: inteiro

inicio
escreval("Digite o valor de A: ")
leia(A)
escreval("Digite o valor de B: ")
leia(B)

escreval("O quadrado da diferença é (A - B)^2")
escreval("O valor abaixo corresponde a resposta da operação")
escreval( "A^2 - 2*A*B + B^2" )
escreval(A^2 - (2*A*B) + B^2)

escreval("A diferença dos quadrados é A^2 - B^2")
escreval("O valor abaixo corresponde a resposta da operação")
escreval("A^2 - B^2")
escreval(A^2 - B^2)




fimalgoritmo
