algoritmo "divisao"
"Exercício VI"
var
v1, v2, quoc, rest: inteiro
inicio

escreval("Mostrar o quociente e resto da divisão")

escreval("Digite um valor inteiro: ")
leia(v1)

escreval("Digite outro valor inteiro")
leia(v2)

quoc <- v1\v2
rest <- v1%v2

escreval("O valor do quociente da divisão destes dois números é: ", quoc)
escreval("O valor do resto da divisão destes dois números é: ", rest)



fimalgoritmo
